#include "getdefinevalue.h"

//得到伤害减免系数
hf_int32 GetDamage_reduction(hf_uint8 level)
{
    switch(level)
    {
    case 1:
        return DEFENSE_1;
    case 2:
        return DEFENSE_2;
    case 3:
        return DEFENSE_3;
    case 4:
        return DEFENSE_4;
    case 5:
        return DEFENSE_5;
    case 6:
        return DEFENSE_6;
    case 7:
        return DEFENSE_7;
    case 8:
        return DEFENSE_8;
    case 9:
        return DEFENSE_9;
    case 10:
        return DEFENSE_10;
    case 11:
        return DEFENSE_11;
    case 12:
        return DEFENSE_12;
    case 13:
        return DEFENSE_13;
    case 14:
        return DEFENSE_14;
    case 15:
        return DEFENSE_15;

    default:
        return 0;
    }
}

//得到怪物死亡奖励经验
hf_uint32 GetRewardExperience(hf_uint8 level)
{
    switch(level)
    {
    case 15:
        return REWARD_EXP15;
    case 16:
        return REWARD_EXP16;
    case 17:
        return REWARD_EXP17;
    case 18:
        return REWARD_EXP18;
    case 19:
        return REWARD_EXP19;
    case 20:
        return REWARD_EXP20;
    case 21:
        return REWARD_EXP21;
    case 22:
        return REWARD_EXP22;
    case 23:
        return REWARD_EXP23;
    case 24:
        return REWARD_EXP24;
    case 25:
        return REWARD_EXP25;
    case 26:
        return REWARD_EXP26;
    case 27:
        return REWARD_EXP27;
    case 28:
        return REWARD_EXP28;
    case 29:
        return REWARD_EXP29;
    case 30:
        return REWARD_EXP30;
    case 31:
        return REWARD_EXP31;
    case 32:
        return REWARD_EXP32;
    case 33:
        return REWARD_EXP33;
    case 34:
        return REWARD_EXP34;
    case 35:
        return REWARD_EXP35;
    case 36:
        return REWARD_EXP36;
    case 37:
        return REWARD_EXP37;
    case 38:
        return REWARD_EXP38;
    case 39:
        return REWARD_EXP39;
    case 40:
        return REWARD_EXP49;
    case 41:
        return REWARD_EXP41;
    case 42:
        return REWARD_EXP42;
    case 43:
        return REWARD_EXP43;
    case 44:
        return REWARD_EXP44;
    case 45:
        return REWARD_EXP45;
    case 46:
        return REWARD_EXP46;
    case 47:
        return REWARD_EXP47;
    case 48:
        return REWARD_EXP48;
    case 49:
        return REWARD_EXP49;
    case 50:
        return REWARD_EXP50;
    case 51:
        return REWARD_EXP51;
    case 52:
        return REWARD_EXP52;
    case 53:
        return REWARD_EXP53;
    case 54:
        return REWARD_EXP54;
    case 55:
        return REWARD_EXP55;
    case 56:
        return REWARD_EXP56;
    case 57:
        return REWARD_EXP57;
    case 58:
        return REWARD_EXP58;
    case 59:
        return REWARD_EXP59;
    case 60:
        return REWARD_EXP60;
    case 61:
        return REWARD_EXP61;
    case 62:
        return REWARD_EXP62;
    case 63:
        return REWARD_EXP63;
    case 64:
        return REWARD_EXP64;
    case 65:
        return REWARD_EXP65;
    case 66:
        return REWARD_EXP66;
    case 67:
        return REWARD_EXP67;
    case 68:
        return REWARD_EXP68;
    case 69:
        return REWARD_EXP69;
    case 70:
        return REWARD_EXP70;
    case 71:
        return REWARD_EXP71;
    case 72:
        return REWARD_EXP72;
    case 73:
        return REWARD_EXP73;
    case 74:
        return REWARD_EXP74;
    case 75:
        return REWARD_EXP75;
    case 76:
        return REWARD_EXP76;
    case 77:
        return REWARD_EXP77;
    case 78:
        return REWARD_EXP78;
    case 79:
        return REWARD_EXP79;
    case 80:
        return REWARD_EXP80;
    case 81:
        return REWARD_EXP81;
    case 82:
        return REWARD_EXP82;
    case 83:
        return REWARD_EXP83;
    case 84:
        return REWARD_EXP84;
    case 85:
        return REWARD_EXP85;
    case 86:
        return REWARD_EXP86;
    case 87:
        return REWARD_EXP87;
    case 88:
        return REWARD_EXP88;
    case 89:
        return REWARD_EXP89;
    case 90:
        return REWARD_EXP90;
    case 91:
        return REWARD_EXP91;
    case 92:
        return REWARD_EXP92;
    case 93:
        return REWARD_EXP93;
    case 94:
        return REWARD_EXP94;
    case 95:
        return REWARD_EXP95;
    case 96:
        return REWARD_EXP96;
    case 97:
        return REWARD_EXP97;
    case 98:
        return REWARD_EXP98;
    case 99:
        return REWARD_EXP99;
    case 100:
        return REWARD_EXP100;
    case 101:
        return REWARD_EXP101;
    case 102:
        return REWARD_EXP102;
    case 103:
        return REWARD_EXP103;
    case 104:
        return REWARD_EXP104;
    case 105:
        return REWARD_EXP105;
    case 106:
        return REWARD_EXP106;
    case 107:
        return REWARD_EXP107;
    case 108:
        return REWARD_EXP108;
    case 109:
        return REWARD_EXP109;
    case 110:
        return REWARD_EXP100;

    default:
        return 0;
    }
}

//得到怪物奖励金钱
hf_uint32 GetRewardMoney(hf_uint8 level)
{
    switch(level)
    {
    case 1:
        return REWARD_MONEY1;
    case 2:
        return REWARD_MONEY2;
    case 3:
        return REWARD_MONEY3;
    case 4:
        return REWARD_MONEY4;
    case 5:
        return REWARD_MONEY5;
    case 6:
        return REWARD_MONEY6;
    case 7:
        return REWARD_MONEY7;
    case 8:
        return REWARD_MONEY8;
    case 9:
        return REWARD_MONEY9;
    case 10:
        return REWARD_MONEY10;
    case 11:
        return REWARD_MONEY11;
    case 12:
        return REWARD_MONEY12;
    case 13:
        return REWARD_MONEY13;
    case 14:
        return REWARD_MONEY14;
    case 15:
        return REWARD_MONEY15;
    case 16:
        return REWARD_MONEY16;
    case 17:
        return REWARD_MONEY17;
    case 18:
        return REWARD_MONEY18;
    case 19:
        return REWARD_MONEY19;
    case 20:
        return REWARD_MONEY20;
    case 21:
        return REWARD_MONEY21;
    case 22:
        return REWARD_MONEY22;
    case 23:
        return REWARD_MONEY23;
    case 24:
        return REWARD_MONEY24;
    case 25:
        return REWARD_MONEY25;
    case 26:
        return REWARD_MONEY26;
    case 27:
        return REWARD_MONEY27;
    case 28:
        return REWARD_MONEY28;
    case 29:
        return REWARD_MONEY29;
    case 30:
        return REWARD_MONEY30;
    case 31:
        return REWARD_MONEY31;
    case 32:
        return REWARD_MONEY32;
    case 33:
        return REWARD_MONEY33;
    case 34:
        return REWARD_MONEY34;
    case 35:
        return REWARD_MONEY35;
    case 36:
        return REWARD_MONEY36;
    case 37:
        return REWARD_MONEY37;
    case 38:
        return REWARD_MONEY38;
    case 39:
        return REWARD_MONEY39;
    case 40:
        return REWARD_MONEY40;
    case 41:
        return REWARD_MONEY41;
    case 42:
        return REWARD_MONEY42;
    case 43:
        return REWARD_MONEY43;
    case 44:
        return REWARD_MONEY44;
    case 45:
        return REWARD_MONEY45;
    case 46:
        return REWARD_MONEY46;
    case 47:
        return REWARD_MONEY47;
    case 48:
        return REWARD_MONEY48;
    case 49:
        return REWARD_MONEY49;
    case 50:
        return REWARD_MONEY50;
    case 51:
        return REWARD_MONEY51;
    case 52:
        return REWARD_MONEY52;
    case 53:
        return REWARD_MONEY53;
    case 54:
        return REWARD_MONEY54;
    case 55:
        return REWARD_MONEY55;
    case 56:
        return REWARD_MONEY56;
    case 57:
        return REWARD_MONEY57;
    case 58:
        return REWARD_MONEY58;
    case 59:
        return REWARD_MONEY59;
    case 60:
        return REWARD_MONEY60;
    case 61:
        return REWARD_MONEY61;
    case 62:
        return REWARD_MONEY62;
    case 63:
        return REWARD_MONEY63;
    case 64:
        return REWARD_MONEY64;
    case 65:
        return REWARD_MONEY65;
    case 66:
        return REWARD_MONEY66;
    case 67:
        return REWARD_MONEY67;
    case 68:
        return REWARD_MONEY68;
    case 69:
        return REWARD_MONEY69;
    case 70:
        return REWARD_MONEY70;
    case 71:
        return REWARD_MONEY71;
    case 72:
        return REWARD_MONEY72;
    case 73:
        return REWARD_MONEY73;
    case 74:
        return REWARD_MONEY74;
    case 75:
        return REWARD_MONEY75;
    case 76:
        return REWARD_MONEY76;
    case 77:
        return REWARD_MONEY77;
    case 78:
        return REWARD_MONEY78;
    case 79:
        return REWARD_MONEY79;
    case 80:
        return REWARD_MONEY80;
    case 81:
        return REWARD_MONEY81;
    case 82:
        return REWARD_MONEY82;
    case 83:
        return REWARD_MONEY83;
    case 84:
        return REWARD_MONEY84;
    case 85:
        return REWARD_MONEY85;
    case 86:
        return REWARD_MONEY86;
    case 87:
        return REWARD_MONEY87;
    case 88:
        return REWARD_MONEY88;
    case 89:
        return REWARD_MONEY89;
    case 90:
        return REWARD_MONEY90;
    case 91:
        return REWARD_MONEY91;
    case 92:
        return REWARD_MONEY92;
    case 93:
        return REWARD_MONEY93;
    case 94:
        return REWARD_MONEY94;
    case 95:
        return REWARD_MONEY95;
    case 96:
        return REWARD_MONEY96;
    case 97:
        return REWARD_MONEY97;
    case 98:
        return REWARD_MONEY98;
    case 99:
        return REWARD_MONEY99;
    case 100:
        return REWARD_MONEY100;
    case 101:
        return REWARD_MONEY101;
    case 102:
        return REWARD_MONEY102;
    case 103:
        return REWARD_MONEY103;
    case 104:
        return REWARD_MONEY104;
    case 105:
        return REWARD_MONEY105;
    case 106:
        return REWARD_MONEY106;
    case 107:
        return REWARD_MONEY107;
    case 108:
        return REWARD_MONEY108;
    case 109:
        return REWARD_MONEY109;
    case 110:
        return REWARD_MONEY110;

    default:
        return 0;
    }
}

//得到升级所需经验
hf_uint32 GetUpgradeExprience(hf_uint8 level)
{
    switch(level)
    {
    case 1:
        return GRADE_1;
    case 2:
        return GRADE_2;
    case 3:
        return GRADE_3;
    case 4:
        return GRADE_4;
    case 5:
        return GRADE_5;
    case 6:
        return GRADE_6;
    case 7:
        return GRADE_7;
    case 8:
        return GRADE_8;
    case 9:
        return GRADE_9;
    case 10:
        return GRADE_10;
    case 11:
        return GRADE_11;
    case 12:
        return GRADE_12;
    case 13:
        return GRADE_13;
    case 14:
        return GRADE_14;
    case 15:
        return GRADE_15;
    case 16:
        return GRADE_16;
    case 17:
        return GRADE_17;
    case 18:
        return GRADE_18;
    case 19 :
        return GRADE_19;
    case 20:
        return GRADE_20;
    case 21:
        return GRADE_21;
    case 22:
        return GRADE_22;
    case 23:
        return GRADE_23;
    case 24:
        return GRADE_24;
    case 25:
        return GRADE_25;
    case 26:
        return GRADE_26;
    case 27:
        return GRADE_27;
    case 28:
        return GRADE_28;
    case 29:
        return GRADE_29;
    case 30:
        return GRADE_30;
    case 31:
        return GRADE_31;
    case 32:
        return GRADE_32;
    case 33:
        return GRADE_33;
    case 34:
        return GRADE_34;
    case 35:
        return GRADE_35;
    case 36:
        return GRADE_36;
    case 37:
        return GRADE_37;
    case 38:
        return GRADE_38;
    case 39:
        return GRADE_39;
    case 40:
        return GRADE_40;
    case 41:
        return GRADE_41;
    case 42:
        return GRADE_42;
    case 43:
        return GRADE_43;
    case 44:
        return GRADE_44;
    case 45:
        return GRADE_45;
    case 46:
        return GRADE_46;
    case 47:
        return GRADE_47;
    case 48:
        return GRADE_48;
    case 49:
        return GRADE_49;
    case 50:
        return GRADE_50;
    case 51:
        return GRADE_51;
    case 52:
        return GRADE_52;
    case 53:
        return GRADE_53;
    case 54:
        return GRADE_54;
    case 55:
        return GRADE_55;
    case 56:
        return GRADE_56;
    case 57:
        return GRADE_57;
    case 58:
        return GRADE_58;
    case 59:
        return GRADE_59;
    case 60:
        return GRADE_60;
    case 61:
        return GRADE_61;
    case 62:
        return GRADE_62;
    case 63:
        return GRADE_63;
    case 64:
        return GRADE_64;
    case 65:
        return GRADE_65;
    case 66:
        return GRADE_66;
    case 67:
        return GRADE_67;
    case 68:
        return GRADE_68;
    case 69:
        return GRADE_69;
    case 70:
        return GRADE_70;
    case 71:
        return GRADE_71;
    case 72:
        return GRADE_72;
    case 73:
        return GRADE_73;
    case 74:
        return GRADE_74;
    case 75:
        return GRADE_75;
    case 76:
        return GRADE_76;
    case 77:
        return GRADE_77;
    case 78:
        return GRADE_78;
    case 79:
        return GRADE_79;
    case 80:
        return GRADE_80;
    case 81:
        return GRADE_81;
    case 82:
        return GRADE_82;
    case 83:
        return GRADE_83;
    case 84:
        return GRADE_84;
    case 85:
        return GRADE_85;
    case 86:
        return GRADE_86;
    case 87:
        return GRADE_87;
    case 88:
        return GRADE_88;
    case 89:
        return GRADE_89;
    case 90:
        return GRADE_90;
    case 91:
        return GRADE_91;
    case 92:
        return GRADE_92;
    case 93:
        return GRADE_93;
    case 94:
        return GRADE_94;
    case 95:
        return GRADE_95;
    case 96:
        return GRADE_96;
    case 97:
        return GRADE_97;
    case 98:
        return GRADE_98;
    case 99:
        return GRADE_99;
    case 100:
        return GRADE_100;
    case 101:
        return GRADE_101;
    case 102:
        return GRADE_102;
    case 103:
        return GRADE_103;
    case 104:
        return GRADE_104;
    case 105:
        return GRADE_105;
    case 106:
        return GRADE_106;
    case 107:
        return GRADE_107;
    case 108:
        return GRADE_108;
    case 109:
        return GRADE_109;
    case 110:
        return GRADE_110;

    default:
        return 0;

    }
}
